import "./global.css";
import SessionWrapper from '../components/shared/SessionWrapper'
import Script from "next/script";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body>
          <div id="fb-root"></div>
          <Script async defer crossOrigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v20.0&appId=1074369130721955"></Script>
          {children}
        </body>
      </html>
    </SessionWrapper>
  )
}
